### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/git-queue#6]
From: https://github.com/josecelano/library-consumer/issues/10

- [ ] Merge updates created by DependantBot and make sure tests pass.
- [ ] Create new issues and link them to the original [POC repo](https://github.com/josecelano/library-consumer/tree/main/.github/actions/git-queue).
- [ ] Remove code from the [template](https://github.com/actions/typescript-action) that we do not need.
- [ ] Add [mega-linter](https://github.com/megalinter/megalinter).
- [ ] Write a basic README for the action.
- [ ] Import GitHub Action code from [POC repo](https://github.com/josecelano/library-consumer/tree/main/.github/actions/git-queue).
- [ ] Improve the README.
- [ ] Publish the beta version of the action and use it on the [POC repo](https://github.com/josecelano/library-consumer/tree/main/.github/actions/git-queue).
- [ ] New conventions definition from https://github.com/josecelano/library-consumer/issues/4 (only definition, docs).
- [ ] Refactor current messages to use new wording (only wording, no protocol literals).
- [ ] Add new queue message "Start Job".
- [ ] Refactor to use a `json` payload to add queue metadata.
- [ ] Change protocol keywords (commit subject).
- [ ] Multi-job queue: allow more than 1 pending job in the queue.

**Comment by josecelano** [comment]
hi @da2ce7 @yeraydavidrodriguez I have slightly changed the roadmap to release a v2-beta to fi #124 asap. I kept #21 and #24 because I think there are almost done.
